### PR TITLE
Clean-up and fixed a few linking problems

### PR DESCRIPTION
**Pull request by kuzeyron**
Just a helping hand to make the code look better.

### CODE REVIEW

**Review by Android-for-Python — COMMENTED** [review]
Thanks for the cleanup.
There one change I don't understand, `from gestures4kivy.screens.....`

Because `screens.py` is part of https://github.com/Android-for-Python/Common-Gestures-Example and not part of https://github.com/Android-for-Python/gestures4kivy/tree/main/src/gestures4kivy it seems the original is correct. What am I missing?

**Comment by kuzeyron** [comment]
> Thanks for the cleanup. There one change I don't understand, `from gestures4kivy.screens.....`
> 
> Because `screens.py` is part of https://github.com/Android-for-Python/Common-Gestures-Example and not part of https://github.com/Android-for-Python/gestures4kivy/tree/main/src/gestures4kivy it seems the original is correct. What am I missing?

I believe the problem is this:
```
gestures4kivy
main.py
design.kv
```
I might be wrong but it seemed like a problem for importing the project the way I'm doing it right now.
From kivylang I use `#:import ZoomImage gestures4kivy.zoomimage.ZoomImage`.
This project should be on pip by the way!

**Comment by Android-for-Python** [comment]
I would not expect the kv import to work, zooimage.py is not in gestures4kivy either.
https://github.com/Android-for-Python/gestures4kivy

gestures4kivy is installed by pip from https://pypi.org/project/gestures4kivy/

Is the local copy of the example in a directory with the same name as the imported package?

**Comment by kuzeyron** [comment]
```
PDF/gestures4kivy:
commongestures.py  gestureboxlayout.py  gesturecanvas.py  gesturelabel.py  screens.py  swipescreen.py  zoomimage.py
```
Is the files in the folder `gestures4kivy`. And anything in the PDF folder is what I mentioned before.

**Comment by Android-for-Python** [comment]
`pip search` has not worked for some time, regardless of the package. And as I have already pointed out you can see gestures4kivy on pypi. And the install instructions are clear https://github.com/Android-for-Python/gestures4kivy#install

I'm going to reject the PR because it introduces a directory name that has the same name as an imported package. Also the new directory contains the contents of the imported package in addition to redundant files.

**Pull request closed without merging**
